using Microsoft.AspNetCore.Mvc;
using GardenGroupIncidentSystem.Services;
using GardenGroupIncidentSystem.Models;
using System;
using System.Linq;

namespace GardenGroupIncidentSystem.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly EmployeeService _employeeService;

        public EmployeeController(EmployeeService employeeService)
        {
            _employeeService = employeeService;
        }

        /// <summary>
        /// Main employee management page
        /// Shows all employees and create form
        /// </summary>
        public IActionResult Index()
        {
            try
            {
                var employees = _employeeService.GetAllEmployees();
                ViewBag.TotalCount = employees.Count;

                var regularCount = _employeeService.GetEmployeesByRole("regular").Count;
                var serviceDeskCount = _employeeService.GetEmployeesByRole("service_desk").Count;

                ViewBag.RegularCount = regularCount;
                ViewBag.ServiceDeskCount = serviceDeskCount;

                return View(employees);
            }
            catch (Exception ex)
            {
                ViewBag.Error = $"Error loading employees: {ex.Message}";
                return View(new System.Collections.Generic.List<Employee>());
            }
        }

        /// <summary>
        /// Create new employee (POST)
        /// Employee ID is auto-generated
        /// </summary>
        [HttpPost]
        public IActionResult Create(string firstName, string lastName,
            string email, string phone, string location, string role, string password)
        {
            try
            {
                // Validate - NO MORE employeeId parameter!
                if (string.IsNullOrEmpty(firstName) || string.IsNullOrEmpty(lastName) ||
                    string.IsNullOrEmpty(password))
                {
                    TempData["Error"] = "First Name, Last Name, and Password are required!";
                    return RedirectToAction("Index");
                }

                // Create employee - ID will be auto-generated
                var employee = new Employee
                {
                    // NO ID HERE - will be auto-generated by repository!
                    Password = password,
                    Role = role,
                    Name = new EmployeeName
                    {
                        FirstName = firstName,
                        LastName = lastName
                    },
                    ContactDetails = new ContactDetails
                    {
                        EmailAddress = email,
                        PhoneNumber = phone,
                        Location = location
                    }
                };

                var created = _employeeService.CreateEmployee(employee);
                TempData["Success"] = $"Employee {created.Id} created successfully!";
            }
            catch (Exception ex)
            {
                TempData["Error"] = $"Failed to create employee: {ex.Message}";
            }

            return RedirectToAction("Index");
        }

        /// <summary>
        /// View single employee details
        /// </summary>
        public IActionResult Details(string id)
        {
            try
            {
                var employee = _employeeService.GetEmployeeById(id);

                if (employee == null)
                {
                    TempData["Error"] = $"Employee {id} not found!";
                    return RedirectToAction("Index");
                }

                return View(employee);
            }
            catch (Exception ex)
            {
                TempData["Error"] = $"Error loading employee: {ex.Message}";
                return RedirectToAction("Index");
            }
        }

        /// <summary>
        /// Search employees
        /// </summary>
        [HttpGet]
        public IActionResult Search(string searchTerm, string roleFilter)
        {
            try
            {
                var employees = _employeeService.GetAllEmployees();

                // Filter by role if specified
                if (!string.IsNullOrEmpty(roleFilter) && roleFilter != "all")
                {
                    employees = employees.Where(e => e.Role == roleFilter).ToList();
                }

                // Filter by search term
                if (!string.IsNullOrEmpty(searchTerm))
                {
                    employees = employees.Where(e =>
                        e.Id.Contains(searchTerm, StringComparison.OrdinalIgnoreCase) ||
                        e.Name.FirstName.Contains(searchTerm, StringComparison.OrdinalIgnoreCase) ||
                        e.Name.LastName.Contains(searchTerm, StringComparison.OrdinalIgnoreCase) ||
                        e.ContactDetails.EmailAddress.Contains(searchTerm, StringComparison.OrdinalIgnoreCase)
                    ).ToList();
                }

                ViewBag.SearchTerm = searchTerm;
                ViewBag.RoleFilter = roleFilter;
                ViewBag.TotalCount = employees.Count;

                var regularCount = employees.Count(e => e.Role == "regular");
                var serviceDeskCount = employees.Count(e => e.Role == "service_desk");

                ViewBag.RegularCount = regularCount;
                ViewBag.ServiceDeskCount = serviceDeskCount;

                return View("Index", employees);
            }
            catch (Exception ex)
            {
                ViewBag.Error = $"Search failed: {ex.Message}";
                return View("Index", new System.Collections.Generic.List<Employee>());
            }
        }
    }
}