using GardenGroupIncidentSystem.Models;
using GardenGroupIncidentSystem.Services.Repositories;
using System;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Text;

namespace GardenGroupIncidentSystem.Services
{
    /// <summary>
    /// Employee Service - Business Logic Layer
    /// Author: [YOUR NAME]
    /// Handles business logic and delegates data access to Repository
    /// 
    /// Design Choice: Service Layer + Repository Pattern
    /// Reason: Separates business logic from data access
    /// Service handles: validation, password hashing, business rules
    /// Repository handles: database operations, ID generation
    /// </summary>
    public class EmployeeService
    {
        private readonly IEmployeeRepository _repository;

        public EmployeeService(IEmployeeRepository repository)
        {
            _repository = repository;
        }

        // ========================================================================
        // CREATE OPERATIONS (with business logic)
        // ========================================================================

        /// <summary>
        /// Creates a new employee with password hashing
        /// Business logic: Validates input and hashes password before storage
        /// ID is auto-generated by repository
        /// </summary>
        public Employee CreateEmployee(Employee employee)
        {
            // Business validation
            if (employee == null)
                throw new ArgumentNullException(nameof(employee));

            if (string.IsNullOrEmpty(employee.Password))
                throw new ArgumentException("Password is required");

            // Business logic: Hash password
            employee.Password = HashPassword(employee.Password);

            // Delegate to repository (ID will be auto-generated)
            return _repository.CreateEmployee(employee);
        }

        /// <summary>
        /// Creates multiple employees with password hashing
        /// </summary>
        public void CreateEmployees(List<Employee> employees)
        {
            if (employees == null || employees.Count == 0)
                throw new ArgumentException("Employee list cannot be empty");

            // Business logic: Hash all passwords
            foreach (var emp in employees)
            {
                if (!string.IsNullOrEmpty(emp.Password))
                {
                    emp.Password = HashPassword(emp.Password);
                }
            }

            _repository.CreateEmployees(employees);
        }

        // ========================================================================
        // READ OPERATIONS (delegated to repository)
        // ========================================================================

        public List<Employee> GetAllEmployees()
        {
            return _repository.GetAllEmployees();
        }

        public Employee GetEmployeeById(string employeeId)
        {
            return _repository.GetEmployeeById(employeeId);
        }

        public List<Employee> GetEmployeesByRole(string role)
        {
            return _repository.GetEmployeesByRole(role);
        }

        public List<Employee> GetEmployeesByIds(List<string> employeeIds)
        {
            return _repository.GetEmployeesByIds(employeeIds);
        }

        public List<Employee> GetEmployeesByRoles(List<string> roles)
        {
            return _repository.GetEmployeesByRoles(roles);
        }

        public List<Employee> GetEmployeesByLocationAndRole(string location, string role)
        {
            return _repository.GetEmployeesByLocationAndRole(location, role);
        }

        public List<Employee> SearchEmployeesByName(string searchTerm)
        {
            return _repository.SearchEmployeesByName(searchTerm);
        }

        // ========================================================================
        // AGGREGATION (delegated to repository)
        // ========================================================================

        public Dictionary<string, int> GetEmployeeCountByRole()
        {
            return _repository.GetEmployeeCountByRole();
        }

        public Dictionary<string, int> GetEmployeeCountByLocation()
        {
            return _repository.GetEmployeeCountByLocation();
        }

        public EmployeeStatistics GetEmployeeStatistics()
        {
            return _repository.GetEmployeeStatistics();
        }

        // ========================================================================
        // HELPER METHODS (delegated to repository)
        // ========================================================================

        public bool EmployeeExists(string employeeId)
        {
            return _repository.EmployeeExists(employeeId);
        }

        public long CountAllEmployees()
        {
            return _repository.CountAllEmployees();
        }

        // ========================================================================
        // BUSINESS LOGIC - PASSWORD HASHING
        // ========================================================================

        /// <summary>
        /// Hashes a password using SHA256
        /// This is business logic, not data access, so it stays in Service
        /// </summary>
        private string HashPassword(string password)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] bytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
                StringBuilder builder = new StringBuilder();

                for (int i = 0; i < bytes.Length; i++)
                {
                    builder.Append(bytes[i].ToString("x2"));
                }

                return builder.ToString();
            }
        }
    }
}